# Generated by Django 5.0.3 on 2024-03-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='entry',
            field=models.TextField(default='ArticleEntry'),
        ),
    ]
