# Generated by Django 5.0.3 on 2024-05-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_name_profile_display_name_alter_profile_email'),
        ('wiki', '0004_article_article_author_article_header_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_author', to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_category', to='wiki.articlecategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='entry',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_author', to='user_management.profile'),
        ),
    ]
