# Generated by Django 5.0.2 on 2024-05-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('user_management', '0002_rename_name_profile_display_name_alter_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createdOn']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='CreatedOn',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='UpdateOn',
            new_name='updatedOn',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articleAuthor', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='article',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentAuthor', to='user_management.profile')),
            ],
            options={
                'ordering': ['createdOn'],
            },
        ),
    ]
